"""add icon column to ingredients

Revision ID: 10625c3b76d1
Revises: f99f4c01510c
Create Date: 2026-05-16 13:32:48.173195

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "10625c3b76d1"
down_revision: str | None = "f99f4c01510c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ingredients", sa.Column("icon", sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ingredients", "icon")
    # ### end Alembic commands ###
