"""add token_prefix to refresh_tokens

Revision ID: 2ea2673576c3
Revises: 8bd69b28d6bd
Create Date: 2026-05-15 16:54:36.077159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ea2673576c3'
down_revision: Union[str, None] = '8bd69b28d6bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add nullable first so existing rows are accepted, then tighten to NOT NULL
    op.add_column('refresh_tokens', sa.Column('token_prefix', sa.String(length=16), nullable=True))
    op.execute("UPDATE refresh_tokens SET token_prefix = substring(token_hash, 1, 16)")
    op.alter_column('refresh_tokens', 'token_prefix', nullable=False)
    op.create_index(op.f('ix_refresh_tokens_token_prefix'), 'refresh_tokens', ['token_prefix'], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_tokens_token_prefix'), table_name='refresh_tokens')
    op.drop_column('refresh_tokens', 'token_prefix')
    # ### end Alembic commands ###
