// This file is auto-generated by @hey-api/openapi-ts

export const $HTTPValidationError = {
  properties: {
    detail: {
      items: {
        $ref: "#/components/schemas/ValidationError",
      },
      type: "array",
      title: "Detail",
    },
  },
  type: "object",
  title: "HTTPValidationError",
} as const;

export const $IngredientCreate = {
  properties: {
    name: {
      type: "string",
      maxLength: 255,
      minLength: 1,
      title: "Name",
    },
    unit: {
      $ref: "#/components/schemas/UnitType",
    },
    portion_size: {
      type: "number",
      exclusiveMinimum: 0,
      title: "Portion Size",
      default: 100,
    },
    kcal: {
      type: "number",
      minimum: 0,
      title: "Kcal",
    },
    protein: {
      type: "number",
      minimum: 0,
      title: "Protein",
    },
    fat: {
      type: "number",
      minimum: 0,
      title: "Fat",
    },
    carbohydrates: {
      type: "number",
      minimum: 0,
      title: "Carbohydrates",
    },
    fiber: {
      type: "number",
      minimum: 0,
      title: "Fiber",
    },
    sodium: {
      type: "number",
      minimum: 0,
      title: "Sodium",
    },
    icon: {
      anyOf: [
        {
          type: "string",
          maxLength: 10,
        },
        {
          type: "null",
        },
      ],
      title: "Icon",
    },
  },
  type: "object",
  required: [
    "name",
    "unit",
    "kcal",
    "protein",
    "fat",
    "carbohydrates",
    "fiber",
    "sodium",
  ],
  title: "IngredientCreate",
} as const;

export const $IngredientDetail = {
  properties: {
    id: {
      type: "integer",
      title: "Id",
    },
    name: {
      type: "string",
      title: "Name",
    },
    unit: {
      $ref: "#/components/schemas/UnitType",
    },
    portion_size: {
      type: "number",
      title: "Portion Size",
    },
    kcal: {
      type: "number",
      title: "Kcal",
    },
    protein: {
      type: "number",
      title: "Protein",
    },
    fat: {
      type: "number",
      title: "Fat",
    },
    carbohydrates: {
      type: "number",
      title: "Carbohydrates",
    },
    fiber: {
      type: "number",
      title: "Fiber",
    },
    sodium: {
      type: "number",
      title: "Sodium",
    },
    is_system: {
      type: "boolean",
      title: "Is System",
    },
    owner_id: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "Owner Id",
    },
    icon: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Icon",
    },
    is_promotion_pending: {
      type: "boolean",
      title: "Is Promotion Pending",
    },
  },
  type: "object",
  required: [
    "id",
    "name",
    "unit",
    "portion_size",
    "kcal",
    "protein",
    "fat",
    "carbohydrates",
    "fiber",
    "sodium",
    "is_system",
    "owner_id",
    "icon",
    "is_promotion_pending",
  ],
  title: "IngredientDetail",
} as const;

export const $IngredientSearchResult = {
  properties: {
    id: {
      type: "integer",
      title: "Id",
    },
    name: {
      type: "string",
      title: "Name",
    },
    unit: {
      $ref: "#/components/schemas/UnitType",
    },
    portion_size: {
      type: "number",
      title: "Portion Size",
    },
    kcal: {
      type: "number",
      title: "Kcal",
    },
    is_system: {
      type: "boolean",
      title: "Is System",
    },
    icon: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Icon",
    },
  },
  type: "object",
  required: ["id", "name", "unit", "portion_size", "kcal", "is_system", "icon"],
  title: "IngredientSearchResult",
} as const;

export const $IngredientUpdate = {
  properties: {
    name: {
      anyOf: [
        {
          type: "string",
          maxLength: 255,
          minLength: 1,
        },
        {
          type: "null",
        },
      ],
      title: "Name",
    },
    unit: {
      anyOf: [
        {
          $ref: "#/components/schemas/UnitType",
        },
        {
          type: "null",
        },
      ],
    },
    portion_size: {
      anyOf: [
        {
          type: "number",
          exclusiveMinimum: 0,
        },
        {
          type: "null",
        },
      ],
      title: "Portion Size",
    },
    kcal: {
      anyOf: [
        {
          type: "number",
          minimum: 0,
        },
        {
          type: "null",
        },
      ],
      title: "Kcal",
    },
    protein: {
      anyOf: [
        {
          type: "number",
          minimum: 0,
        },
        {
          type: "null",
        },
      ],
      title: "Protein",
    },
    fat: {
      anyOf: [
        {
          type: "number",
          minimum: 0,
        },
        {
          type: "null",
        },
      ],
      title: "Fat",
    },
    carbohydrates: {
      anyOf: [
        {
          type: "number",
          minimum: 0,
        },
        {
          type: "null",
        },
      ],
      title: "Carbohydrates",
    },
    fiber: {
      anyOf: [
        {
          type: "number",
          minimum: 0,
        },
        {
          type: "null",
        },
      ],
      title: "Fiber",
    },
    sodium: {
      anyOf: [
        {
          type: "number",
          minimum: 0,
        },
        {
          type: "null",
        },
      ],
      title: "Sodium",
    },
    icon: {
      anyOf: [
        {
          type: "string",
          maxLength: 10,
        },
        {
          type: "null",
        },
      ],
      title: "Icon",
    },
  },
  type: "object",
  title: "IngredientUpdate",
} as const;

export const $LoginRequest = {
  properties: {
    username: {
      type: "string",
      title: "Username",
    },
    password: {
      type: "string",
      title: "Password",
    },
  },
  type: "object",
  required: ["username", "password"],
  title: "LoginRequest",
} as const;

export const $RegisterRequest = {
  properties: {
    username: {
      type: "string",
      maxLength: 64,
      minLength: 3,
      title: "Username",
    },
    email: {
      type: "string",
      format: "email",
      title: "Email",
    },
    password: {
      type: "string",
      minLength: 8,
      title: "Password",
    },
  },
  type: "object",
  required: ["username", "email", "password"],
  title: "RegisterRequest",
} as const;

export const $TokenResponse = {
  properties: {
    access_token: {
      type: "string",
      title: "Access Token",
    },
    token_type: {
      type: "string",
      title: "Token Type",
      default: "bearer",
    },
  },
  type: "object",
  required: ["access_token"],
  title: "TokenResponse",
} as const;

export const $UnitType = {
  type: "string",
  enum: ["g", "ml", "tablespoon", "piece"],
  title: "UnitType",
} as const;

export const $ValidationError = {
  properties: {
    loc: {
      items: {
        anyOf: [
          {
            type: "string",
          },
          {
            type: "integer",
          },
        ],
      },
      type: "array",
      title: "Location",
    },
    msg: {
      type: "string",
      title: "Message",
    },
    type: {
      type: "string",
      title: "Error Type",
    },
    input: {
      title: "Input",
    },
    ctx: {
      type: "object",
      title: "Context",
    },
  },
  type: "object",
  required: ["loc", "msg", "type"],
  title: "ValidationError",
} as const;
