// This file is auto-generated by @hey-api/openapi-ts

export const $BulkImportItem = {
  properties: {
    name: {
      type: "string",
      maxLength: 255,
      minLength: 1,
      title: "Name",
    },
    unit: {
      $ref: "#/components/schemas/UnitType",
    },
    portion_size: {
      type: "number",
      exclusiveMinimum: 0,
      title: "Portion Size",
      default: 100,
    },
    kcal: {
      type: "number",
      minimum: 0,
      title: "Kcal",
    },
    protein: {
      type: "number",
      minimum: 0,
      title: "Protein",
    },
    fat: {
      type: "number",
      minimum: 0,
      title: "Fat",
    },
    carbohydrates: {
      type: "number",
      minimum: 0,
      title: "Carbohydrates",
    },
    fiber: {
      type: "number",
      minimum: 0,
      title: "Fiber",
    },
    sodium: {
      type: "number",
      minimum: 0,
      title: "Sodium",
    },
    icon: {
      anyOf: [
        {
          type: "string",
          maxLength: 10,
        },
        {
          type: "null",
        },
      ],
      title: "Icon",
    },
  },
  type: "object",
  required: [
    "name",
    "unit",
    "kcal",
    "protein",
    "fat",
    "carbohydrates",
    "fiber",
    "sodium",
  ],
  title: "BulkImportItem",
} as const;

export const $BulkImportResult = {
  properties: {
    created: {
      type: "integer",
      title: "Created",
    },
    updated: {
      type: "integer",
      title: "Updated",
    },
    total: {
      type: "integer",
      title: "Total",
    },
  },
  type: "object",
  required: ["created", "updated", "total"],
  title: "BulkImportResult",
} as const;

export const $CookRequest = {
  properties: {
    ingredient_amounts: {
      items: {
        $ref: "#/components/schemas/RecipeIngredientIn",
      },
      type: "array",
      title: "Ingredient Amounts",
    },
    extra_kcal: {
      type: "number",
      minimum: 0,
      title: "Extra Kcal",
      default: 0,
    },
    cooked_weight_g: {
      type: "number",
      exclusiveMinimum: 0,
      title: "Cooked Weight G",
    },
  },
  type: "object",
  required: ["ingredient_amounts", "cooked_weight_g"],
  title: "CookRequest",
} as const;

export const $HTTPValidationError = {
  properties: {
    detail: {
      items: {
        $ref: "#/components/schemas/ValidationError",
      },
      type: "array",
      title: "Detail",
    },
  },
  type: "object",
  title: "HTTPValidationError",
} as const;

export const $IngredientCreate = {
  properties: {
    name: {
      type: "string",
      maxLength: 255,
      minLength: 1,
      title: "Name",
    },
    unit: {
      $ref: "#/components/schemas/UnitType",
    },
    portion_size: {
      type: "number",
      exclusiveMinimum: 0,
      title: "Portion Size",
      default: 100,
    },
    kcal: {
      type: "number",
      minimum: 0,
      title: "Kcal",
    },
    protein: {
      type: "number",
      minimum: 0,
      title: "Protein",
    },
    fat: {
      type: "number",
      minimum: 0,
      title: "Fat",
    },
    carbohydrates: {
      type: "number",
      minimum: 0,
      title: "Carbohydrates",
    },
    fiber: {
      type: "number",
      minimum: 0,
      title: "Fiber",
    },
    sodium: {
      type: "number",
      minimum: 0,
      title: "Sodium",
    },
    icon: {
      anyOf: [
        {
          type: "string",
          maxLength: 10,
        },
        {
          type: "null",
        },
      ],
      title: "Icon",
    },
  },
  type: "object",
  required: [
    "name",
    "unit",
    "kcal",
    "protein",
    "fat",
    "carbohydrates",
    "fiber",
    "sodium",
  ],
  title: "IngredientCreate",
} as const;

export const $IngredientDetail = {
  properties: {
    id: {
      type: "integer",
      title: "Id",
    },
    name: {
      type: "string",
      title: "Name",
    },
    unit: {
      $ref: "#/components/schemas/UnitType",
    },
    portion_size: {
      type: "number",
      title: "Portion Size",
    },
    kcal: {
      type: "number",
      title: "Kcal",
    },
    protein: {
      type: "number",
      title: "Protein",
    },
    fat: {
      type: "number",
      title: "Fat",
    },
    carbohydrates: {
      type: "number",
      title: "Carbohydrates",
    },
    fiber: {
      type: "number",
      title: "Fiber",
    },
    sodium: {
      type: "number",
      title: "Sodium",
    },
    is_system: {
      type: "boolean",
      title: "Is System",
    },
    owner_id: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "Owner Id",
    },
    icon: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Icon",
    },
    is_promotion_pending: {
      type: "boolean",
      title: "Is Promotion Pending",
    },
    promotion_rejection_note: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Promotion Rejection Note",
    },
  },
  type: "object",
  required: [
    "id",
    "name",
    "unit",
    "portion_size",
    "kcal",
    "protein",
    "fat",
    "carbohydrates",
    "fiber",
    "sodium",
    "is_system",
    "owner_id",
    "icon",
    "is_promotion_pending",
    "promotion_rejection_note",
  ],
  title: "IngredientDetail",
} as const;

export const $IngredientSearchResult = {
  properties: {
    id: {
      type: "integer",
      title: "Id",
    },
    name: {
      type: "string",
      title: "Name",
    },
    unit: {
      $ref: "#/components/schemas/UnitType",
    },
    portion_size: {
      type: "number",
      title: "Portion Size",
    },
    kcal: {
      type: "number",
      title: "Kcal",
    },
    is_system: {
      type: "boolean",
      title: "Is System",
    },
    icon: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Icon",
    },
  },
  type: "object",
  required: ["id", "name", "unit", "portion_size", "kcal", "is_system", "icon"],
  title: "IngredientSearchResult",
} as const;

export const $IngredientUpdate = {
  properties: {
    name: {
      anyOf: [
        {
          type: "string",
          maxLength: 255,
          minLength: 1,
        },
        {
          type: "null",
        },
      ],
      title: "Name",
    },
    unit: {
      anyOf: [
        {
          $ref: "#/components/schemas/UnitType",
        },
        {
          type: "null",
        },
      ],
    },
    portion_size: {
      anyOf: [
        {
          type: "number",
          exclusiveMinimum: 0,
        },
        {
          type: "null",
        },
      ],
      title: "Portion Size",
    },
    kcal: {
      anyOf: [
        {
          type: "number",
          minimum: 0,
        },
        {
          type: "null",
        },
      ],
      title: "Kcal",
    },
    protein: {
      anyOf: [
        {
          type: "number",
          minimum: 0,
        },
        {
          type: "null",
        },
      ],
      title: "Protein",
    },
    fat: {
      anyOf: [
        {
          type: "number",
          minimum: 0,
        },
        {
          type: "null",
        },
      ],
      title: "Fat",
    },
    carbohydrates: {
      anyOf: [
        {
          type: "number",
          minimum: 0,
        },
        {
          type: "null",
        },
      ],
      title: "Carbohydrates",
    },
    fiber: {
      anyOf: [
        {
          type: "number",
          minimum: 0,
        },
        {
          type: "null",
        },
      ],
      title: "Fiber",
    },
    sodium: {
      anyOf: [
        {
          type: "number",
          minimum: 0,
        },
        {
          type: "null",
        },
      ],
      title: "Sodium",
    },
    icon: {
      anyOf: [
        {
          type: "string",
          maxLength: 10,
        },
        {
          type: "null",
        },
      ],
      title: "Icon",
    },
  },
  type: "object",
  title: "IngredientUpdate",
} as const;

export const $LoginRequest = {
  properties: {
    username: {
      type: "string",
      title: "Username",
    },
    password: {
      type: "string",
      title: "Password",
    },
  },
  type: "object",
  required: ["username", "password"],
  title: "LoginRequest",
} as const;

export const $MacroValues = {
  properties: {
    kcal: {
      type: "number",
      title: "Kcal",
    },
    protein: {
      type: "number",
      title: "Protein",
    },
    fat: {
      type: "number",
      title: "Fat",
    },
    carbohydrates: {
      type: "number",
      title: "Carbohydrates",
    },
    fiber: {
      type: "number",
      title: "Fiber",
    },
    sodium: {
      type: "number",
      title: "Sodium",
    },
  },
  type: "object",
  required: ["kcal", "protein", "fat", "carbohydrates", "fiber", "sodium"],
  title: "MacroValues",
} as const;

export const $NutritionResult = {
  properties: {
    totals: {
      $ref: "#/components/schemas/MacroValues",
    },
    per_100g: {
      $ref: "#/components/schemas/MacroValues",
    },
  },
  type: "object",
  required: ["totals", "per_100g"],
  title: "NutritionResult",
} as const;

export const $PromotionRejectRequest = {
  properties: {
    rejection_note: {
      type: "string",
      maxLength: 1000,
      minLength: 1,
      title: "Rejection Note",
    },
  },
  type: "object",
  required: ["rejection_note"],
  title: "PromotionRejectRequest",
} as const;

export const $RecipeCreate = {
  properties: {
    name: {
      type: "string",
      maxLength: 255,
      minLength: 1,
      title: "Name",
    },
    description: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Description",
    },
    ingredients: {
      items: {
        $ref: "#/components/schemas/RecipeIngredientInput",
      },
      type: "array",
      title: "Ingredients",
    },
  },
  type: "object",
  required: ["name"],
  title: "RecipeCreate",
} as const;

export const $RecipeDetail = {
  properties: {
    id: {
      type: "integer",
      title: "Id",
    },
    owner_id: {
      type: "integer",
      title: "Owner Id",
    },
    name: {
      type: "string",
      title: "Name",
    },
    description: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Description",
    },
    last_cooked_at: {
      anyOf: [
        {
          type: "string",
          format: "date-time",
        },
        {
          type: "null",
        },
      ],
      title: "Last Cooked At",
    },
    last_cooked_weight_g: {
      anyOf: [
        {
          type: "number",
        },
        {
          type: "null",
        },
      ],
      title: "Last Cooked Weight G",
    },
    created_at: {
      type: "string",
      format: "date-time",
      title: "Created At",
    },
    updated_at: {
      type: "string",
      format: "date-time",
      title: "Updated At",
    },
    ingredients: {
      items: {
        $ref: "#/components/schemas/RecipeIngredientItem",
      },
      type: "array",
      title: "Ingredients",
    },
  },
  type: "object",
  required: [
    "id",
    "owner_id",
    "name",
    "description",
    "last_cooked_at",
    "last_cooked_weight_g",
    "created_at",
    "updated_at",
    "ingredients",
  ],
  title: "RecipeDetail",
  description: "Full recipe with ingredient list, returned by GET /recipes/{id}.",
} as const;

export const $RecipeDuplicateResponse = {
  properties: {
    id: {
      type: "integer",
      title: "Id",
    },
  },
  type: "object",
  required: ["id"],
  title: "RecipeDuplicateResponse",
} as const;

export const $RecipeIngredientIn = {
  properties: {
    ingredient_id: {
      type: "integer",
      title: "Ingredient Id",
    },
    amount: {
      type: "number",
      exclusiveMinimum: 0,
      title: "Amount",
    },
  },
  type: "object",
  required: ["ingredient_id", "amount"],
  title: "RecipeIngredientIn",
  description: "Ingredient amount submitted for a cooking session.",
} as const;

export const $RecipeIngredientInput = {
  properties: {
    ingredient_id: {
      type: "integer",
      title: "Ingredient Id",
    },
    amount: {
      type: "number",
      exclusiveMinimum: 0,
      title: "Amount",
    },
    display_order: {
      type: "integer",
      minimum: 0,
      title: "Display Order",
      default: 0,
    },
  },
  type: "object",
  required: ["ingredient_id", "amount"],
  title: "RecipeIngredientInput",
  description:
    "Ingredient row submitted by the client when creating/updating a recipe.",
} as const;

export const $RecipeIngredientItem = {
  properties: {
    id: {
      type: "integer",
      title: "Id",
    },
    ingredient_id: {
      type: "integer",
      title: "Ingredient Id",
    },
    amount: {
      type: "number",
      title: "Amount",
    },
    display_order: {
      type: "integer",
      title: "Display Order",
    },
    ingredient: {
      $ref: "#/components/schemas/IngredientDetail",
    },
  },
  type: "object",
  required: ["id", "ingredient_id", "amount", "display_order", "ingredient"],
  title: "RecipeIngredientItem",
  description: "Embedded ingredient row inside a recipe response.",
} as const;

export const $RecipeSummary = {
  properties: {
    id: {
      type: "integer",
      title: "Id",
    },
    name: {
      type: "string",
      title: "Name",
    },
    description: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Description",
    },
    last_cooked_at: {
      anyOf: [
        {
          type: "string",
          format: "date-time",
        },
        {
          type: "null",
        },
      ],
      title: "Last Cooked At",
    },
    last_cooked_weight_g: {
      anyOf: [
        {
          type: "number",
        },
        {
          type: "null",
        },
      ],
      title: "Last Cooked Weight G",
    },
    created_at: {
      type: "string",
      format: "date-time",
      title: "Created At",
    },
    updated_at: {
      type: "string",
      format: "date-time",
      title: "Updated At",
    },
  },
  type: "object",
  required: [
    "id",
    "name",
    "description",
    "last_cooked_at",
    "last_cooked_weight_g",
    "created_at",
    "updated_at",
  ],
  title: "RecipeSummary",
  description: "Light summary returned in list views.",
} as const;

export const $RecipeUpdate = {
  properties: {
    name: {
      anyOf: [
        {
          type: "string",
          maxLength: 255,
          minLength: 1,
        },
        {
          type: "null",
        },
      ],
      title: "Name",
    },
    description: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Description",
    },
    ingredients: {
      anyOf: [
        {
          items: {
            $ref: "#/components/schemas/RecipeIngredientInput",
          },
          type: "array",
        },
        {
          type: "null",
        },
      ],
      title: "Ingredients",
    },
  },
  type: "object",
  title: "RecipeUpdate",
} as const;

export const $RegisterRequest = {
  properties: {
    username: {
      type: "string",
      maxLength: 64,
      minLength: 3,
      title: "Username",
    },
    email: {
      type: "string",
      format: "email",
      title: "Email",
    },
    password: {
      type: "string",
      minLength: 8,
      title: "Password",
    },
  },
  type: "object",
  required: ["username", "email", "password"],
  title: "RegisterRequest",
} as const;

export const $TokenResponse = {
  properties: {
    access_token: {
      type: "string",
      title: "Access Token",
    },
    token_type: {
      type: "string",
      title: "Token Type",
      default: "bearer",
    },
  },
  type: "object",
  required: ["access_token"],
  title: "TokenResponse",
} as const;

export const $UnitType = {
  type: "string",
  enum: ["g", "ml", "tablespoon", "piece"],
  title: "UnitType",
} as const;

export const $UserActivateRequest = {
  properties: {
    is_active: {
      type: "boolean",
      title: "Is Active",
    },
  },
  type: "object",
  required: ["is_active"],
  title: "UserActivateRequest",
} as const;

export const $UserAdminResponse = {
  properties: {
    id: {
      type: "integer",
      title: "Id",
    },
    username: {
      type: "string",
      title: "Username",
    },
    email: {
      type: "string",
      title: "Email",
    },
    role: {
      $ref: "#/components/schemas/UserRole",
    },
    is_active: {
      type: "boolean",
      title: "Is Active",
    },
  },
  type: "object",
  required: ["id", "username", "email", "role", "is_active"],
  title: "UserAdminResponse",
} as const;

export const $UserRole = {
  type: "string",
  enum: ["user", "admin"],
  title: "UserRole",
} as const;

export const $UserRoleRequest = {
  properties: {
    role: {
      $ref: "#/components/schemas/UserRole",
    },
  },
  type: "object",
  required: ["role"],
  title: "UserRoleRequest",
} as const;

export const $ValidationError = {
  properties: {
    loc: {
      items: {
        anyOf: [
          {
            type: "string",
          },
          {
            type: "integer",
          },
        ],
      },
      type: "array",
      title: "Location",
    },
    msg: {
      type: "string",
      title: "Message",
    },
    type: {
      type: "string",
      title: "Error Type",
    },
    input: {
      title: "Input",
    },
    ctx: {
      type: "object",
      title: "Context",
    },
  },
  type: "object",
  required: ["loc", "msg", "type"],
  title: "ValidationError",
} as const;
