// This file is auto-generated by @hey-api/openapi-ts

export const $HTTPValidationError = {
  properties: {
    detail: {
      items: {
        $ref: "#/components/schemas/ValidationError",
      },
      type: "array",
      title: "Detail",
    },
  },
  type: "object",
  title: "HTTPValidationError",
} as const;

export const $LoginRequest = {
  properties: {
    username: {
      type: "string",
      title: "Username",
    },
    password: {
      type: "string",
      title: "Password",
    },
  },
  type: "object",
  required: ["username", "password"],
  title: "LoginRequest",
} as const;

export const $RegisterRequest = {
  properties: {
    username: {
      type: "string",
      maxLength: 64,
      minLength: 3,
      title: "Username",
    },
    email: {
      type: "string",
      format: "email",
      title: "Email",
    },
    password: {
      type: "string",
      minLength: 8,
      title: "Password",
    },
  },
  type: "object",
  required: ["username", "email", "password"],
  title: "RegisterRequest",
} as const;

export const $TokenResponse = {
  properties: {
    access_token: {
      type: "string",
      title: "Access Token",
    },
    token_type: {
      type: "string",
      title: "Token Type",
      default: "bearer",
    },
  },
  type: "object",
  required: ["access_token"],
  title: "TokenResponse",
} as const;

export const $ValidationError = {
  properties: {
    loc: {
      items: {
        anyOf: [
          {
            type: "string",
          },
          {
            type: "integer",
          },
        ],
      },
      type: "array",
      title: "Location",
    },
    msg: {
      type: "string",
      title: "Message",
    },
    type: {
      type: "string",
      title: "Error Type",
    },
    input: {
      title: "Input",
    },
    ctx: {
      type: "object",
      title: "Context",
    },
  },
  type: "object",
  required: ["loc", "msg", "type"],
  title: "ValidationError",
} as const;
