// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from "./core/CancelablePromise";
import { OpenAPI } from "./core/OpenAPI";
import { request as __request } from "./core/request";
import type {
  RegisterAuthRegisterPostData,
  RegisterAuthRegisterPostResponse,
  LoginAuthLoginPostData,
  LoginAuthLoginPostResponse,
  RefreshAuthRefreshPostResponse,
  LogoutAuthLogoutPostResponse,
  HealthHealthGetResponse,
} from "./types.gen";

/**
 * Register
 * @param data The data for the request.
 * @param data.requestBody
 * @returns TokenResponse Successful Response
 * @throws ApiError
 */
export const registerAuthRegisterPost = (
  data: RegisterAuthRegisterPostData
): CancelablePromise<RegisterAuthRegisterPostResponse> => {
  return __request(OpenAPI, {
    method: "POST",
    url: "/auth/register",
    body: data.requestBody,
    mediaType: "application/json",
    errors: {
      422: "Validation Error",
    },
  });
};

/**
 * Login
 * @param data The data for the request.
 * @param data.requestBody
 * @returns TokenResponse Successful Response
 * @throws ApiError
 */
export const loginAuthLoginPost = (
  data: LoginAuthLoginPostData
): CancelablePromise<LoginAuthLoginPostResponse> => {
  return __request(OpenAPI, {
    method: "POST",
    url: "/auth/login",
    body: data.requestBody,
    mediaType: "application/json",
    errors: {
      422: "Validation Error",
    },
  });
};

/**
 * Refresh
 * The refresh token is sent automatically as an HttpOnly cookie by the browser.
 * No explicit cookie injection is needed — credentials are included via
 * `WITH_CREDENTIALS: true` on the OpenAPI config.
 * @returns TokenResponse Successful Response
 * @throws ApiError
 */
export const refreshAuthRefreshPost =
  (): CancelablePromise<RefreshAuthRefreshPostResponse> => {
    return __request(OpenAPI, {
      method: "POST",
      url: "/auth/refresh",
      errors: {
        422: "Validation Error",
      },
    });
  };

/**
 * Logout
 * The refresh token is sent automatically as an HttpOnly cookie by the browser.
 * No explicit cookie injection is needed — credentials are included via
 * `WITH_CREDENTIALS: true` on the OpenAPI config.
 * @returns void Successful Response
 * @throws ApiError
 */
export const logoutAuthLogoutPost =
  (): CancelablePromise<LogoutAuthLogoutPostResponse> => {
    return __request(OpenAPI, {
      method: "POST",
      url: "/auth/logout",
      errors: {
        422: "Validation Error",
      },
    });
  };

/**
 * Health
 * @returns string Successful Response
 * @throws ApiError
 */
export const healthHealthGet = (): CancelablePromise<HealthHealthGetResponse> => {
  return __request(OpenAPI, {
    method: "GET",
    url: "/health",
  });
};
