// This file is auto-generated by @hey-api/openapi-ts

export type HTTPValidationError = {
  detail?: Array<ValidationError>;
};

export type IngredientCreate = {
  name: string;
  unit: UnitType;
  portion_size?: number;
  kcal: number;
  protein: number;
  fat: number;
  carbohydrates: number;
  fiber: number;
  sodium: number;
  icon?: string | null;
};

export type IngredientDetail = {
  id: number;
  name: string;
  unit: UnitType;
  portion_size: number;
  kcal: number;
  protein: number;
  fat: number;
  carbohydrates: number;
  fiber: number;
  sodium: number;
  is_system: boolean;
  owner_id: number | null;
  icon: string | null;
  is_promotion_pending: boolean;
};

export type IngredientSearchResult = {
  id: number;
  name: string;
  unit: UnitType;
  portion_size: number;
  kcal: number;
  is_system: boolean;
  icon: string | null;
};

export type IngredientUpdate = {
  name?: string | null;
  unit?: UnitType | null;
  portion_size?: number | null;
  kcal?: number | null;
  protein?: number | null;
  fat?: number | null;
  carbohydrates?: number | null;
  fiber?: number | null;
  sodium?: number | null;
  icon?: string | null;
};

export type LoginRequest = {
  username: string;
  password: string;
};

export type RegisterRequest = {
  username: string;
  email: string;
  password: string;
};

export type TokenResponse = {
  access_token: string;
  token_type?: string;
};

export type UnitType = "g" | "ml" | "tablespoon" | "piece";

export type ValidationError = {
  loc: Array<string | number>;
  msg: string;
  type: string;
  input?: unknown;
  ctx?: {
    [key: string]: unknown;
  };
};

export type RegisterAuthRegisterPostData = {
  requestBody: RegisterRequest;
};

export type RegisterAuthRegisterPostResponse = TokenResponse;

export type LoginAuthLoginPostData = {
  requestBody: LoginRequest;
};

export type LoginAuthLoginPostResponse = TokenResponse;

export type RefreshAuthRefreshPostData = {
  refreshToken?: string | null;
};

export type RefreshAuthRefreshPostResponse = TokenResponse;

export type LogoutAuthLogoutPostData = {
  refreshToken?: string | null;
};

export type LogoutAuthLogoutPostResponse = void;

export type SearchIngredientsIngredientsSearchGetData = {
  limit?: number;
  q: string;
  unit?: UnitType | null;
};

export type SearchIngredientsIngredientsSearchGetResponse =
  Array<IngredientSearchResult>;

export type GetIngredientIngredientsIngredientIdGetData = {
  ingredientId: number;
};

export type GetIngredientIngredientsIngredientIdGetResponse = IngredientDetail;

export type UpdateIngredientIngredientsIngredientIdPatchData = {
  ingredientId: number;
  requestBody: IngredientUpdate;
};

export type UpdateIngredientIngredientsIngredientIdPatchResponse = IngredientDetail;

export type DeleteIngredientIngredientsIngredientIdDeleteData = {
  ingredientId: number;
};

export type DeleteIngredientIngredientsIngredientIdDeleteResponse = void;

export type CreateIngredientIngredientsPostData = {
  requestBody: IngredientCreate;
};

export type CreateIngredientIngredientsPostResponse = IngredientDetail;

export type PromoteIngredientIngredientsIngredientIdPromotePostData = {
  ingredientId: number;
};

export type PromoteIngredientIngredientsIngredientIdPromotePostResponse =
  IngredientDetail;

export type HealthHealthGetResponse = {
  [key: string]: string;
};

export type $OpenApiTs = {
  "/auth/register": {
    post: {
      req: RegisterAuthRegisterPostData;
      res: {
        /**
         * Successful Response
         */
        201: TokenResponse;
        /**
         * Validation Error
         */
        422: HTTPValidationError;
      };
    };
  };
  "/auth/login": {
    post: {
      req: LoginAuthLoginPostData;
      res: {
        /**
         * Successful Response
         */
        200: TokenResponse;
        /**
         * Validation Error
         */
        422: HTTPValidationError;
      };
    };
  };
  "/auth/refresh": {
    post: {
      req: RefreshAuthRefreshPostData;
      res: {
        /**
         * Successful Response
         */
        200: TokenResponse;
        /**
         * Validation Error
         */
        422: HTTPValidationError;
      };
    };
  };
  "/auth/logout": {
    post: {
      req: LogoutAuthLogoutPostData;
      res: {
        /**
         * Successful Response
         */
        204: void;
        /**
         * Validation Error
         */
        422: HTTPValidationError;
      };
    };
  };
  "/ingredients/search": {
    get: {
      req: SearchIngredientsIngredientsSearchGetData;
      res: {
        /**
         * Successful Response
         */
        200: Array<IngredientSearchResult>;
        /**
         * Validation Error
         */
        422: HTTPValidationError;
      };
    };
  };
  "/ingredients/{ingredient_id}": {
    get: {
      req: GetIngredientIngredientsIngredientIdGetData;
      res: {
        /**
         * Successful Response
         */
        200: IngredientDetail;
        /**
         * Validation Error
         */
        422: HTTPValidationError;
      };
    };
    patch: {
      req: UpdateIngredientIngredientsIngredientIdPatchData;
      res: {
        /**
         * Successful Response
         */
        200: IngredientDetail;
        /**
         * Validation Error
         */
        422: HTTPValidationError;
      };
    };
    delete: {
      req: DeleteIngredientIngredientsIngredientIdDeleteData;
      res: {
        /**
         * Successful Response
         */
        204: void;
        /**
         * Validation Error
         */
        422: HTTPValidationError;
      };
    };
  };
  "/ingredients": {
    post: {
      req: CreateIngredientIngredientsPostData;
      res: {
        /**
         * Successful Response
         */
        201: IngredientDetail;
        /**
         * Validation Error
         */
        422: HTTPValidationError;
      };
    };
  };
  "/ingredients/{ingredient_id}/promote": {
    post: {
      req: PromoteIngredientIngredientsIngredientIdPromotePostData;
      res: {
        /**
         * Successful Response
         */
        200: IngredientDetail;
        /**
         * Validation Error
         */
        422: HTTPValidationError;
      };
    };
  };
  "/health": {
    get: {
      res: {
        /**
         * Successful Response
         */
        200: {
          [key: string]: string;
        };
      };
    };
  };
};
