// This file is auto-generated by @hey-api/openapi-ts

export type BulkImportItem = {
  name: string;
  unit: UnitType;
  portion_size?: number;
  kcal: number;
  protein: number;
  fat: number;
  carbohydrates: number;
  fiber: number;
  sodium: number;
  icon?: string | null;
};

export type BulkImportResult = {
  created: number;
  updated: number;
  total: number;
};

export type CookRequest = {
  ingredient_amounts: Array<RecipeIngredientIn>;
  extra_kcal?: number;
  cooked_weight_g: number;
};

export type HTTPValidationError = {
  detail?: Array<ValidationError>;
};

export type IngredientCreate = {
  name: string;
  unit: UnitType;
  portion_size?: number;
  kcal: number;
  protein: number;
  fat: number;
  carbohydrates: number;
  fiber: number;
  sodium: number;
  icon?: string | null;
};

export type IngredientDetail = {
  id: number;
  name: string;
  unit: UnitType;
  portion_size: number;
  kcal: number;
  protein: number;
  fat: number;
  carbohydrates: number;
  fiber: number;
  sodium: number;
  is_system: boolean;
  owner_id: number | null;
  icon: string | null;
  is_promotion_pending: boolean;
  promotion_rejection_note: string | null;
};

export type IngredientSearchResult = {
  id: number;
  name: string;
  unit: UnitType;
  portion_size: number;
  kcal: number;
  is_system: boolean;
  icon: string | null;
};

export type IngredientUpdate = {
  name?: string | null;
  unit?: UnitType | null;
  portion_size?: number | null;
  kcal?: number | null;
  protein?: number | null;
  fat?: number | null;
  carbohydrates?: number | null;
  fiber?: number | null;
  sodium?: number | null;
  icon?: string | null;
};

export type LoginRequest = {
  username: string;
  password: string;
};

export type MacroValues = {
  kcal: number;
  protein: number;
  fat: number;
  carbohydrates: number;
  fiber: number;
  sodium: number;
};

export type NutritionResult = {
  totals: MacroValues;
  per_100g: MacroValues;
};

export type PromotionRejectRequest = {
  rejection_note: string;
};

export type RecipeCreate = {
  name: string;
  description?: string | null;
  ingredients?: Array<RecipeIngredientInput>;
};

/**
 * Full recipe with ingredient list, returned by GET /recipes/{id}.
 */
export type RecipeDetail = {
  id: number;
  owner_id: number;
  name: string;
  description: string | null;
  last_cooked_at: string | null;
  last_cooked_weight_g: number | null;
  created_at: string;
  updated_at: string;
  ingredients: Array<RecipeIngredientItem>;
};

export type RecipeDuplicateResponse = {
  id: number;
};

/**
 * Ingredient amount submitted for a cooking session.
 */
export type RecipeIngredientIn = {
  ingredient_id: number;
  amount: number;
};

/**
 * Ingredient row submitted by the client when creating/updating a recipe.
 */
export type RecipeIngredientInput = {
  ingredient_id: number;
  amount: number;
  display_order?: number;
};

/**
 * Embedded ingredient row inside a recipe response.
 */
export type RecipeIngredientItem = {
  id: number;
  ingredient_id: number;
  amount: number;
  display_order: number;
  ingredient: IngredientDetail;
};

/**
 * Light summary returned in list views.
 */
export type RecipeSummary = {
  id: number;
  name: string;
  description: string | null;
  last_cooked_at: string | null;
  last_cooked_weight_g: number | null;
  created_at: string;
  updated_at: string;
};

export type RecipeUpdate = {
  name?: string | null;
  description?: string | null;
  ingredients?: Array<RecipeIngredientInput> | null;
};

export type RegisterRequest = {
  username: string;
  email: string;
  password: string;
};

export type TokenResponse = {
  access_token: string;
  token_type?: string;
};

export type UnitType = "g" | "ml" | "tablespoon" | "piece";

export type UserActivateRequest = {
  is_active: boolean;
};

export type UserAdminResponse = {
  id: number;
  username: string;
  email: string;
  role: UserRole;
  is_active: boolean;
};

export type UserRole = "user" | "admin";

export type UserRoleRequest = {
  role: UserRole;
};

export type ValidationError = {
  loc: Array<string | number>;
  msg: string;
  type: string;
  input?: unknown;
  ctx?: {
    [key: string]: unknown;
  };
};

export type RegisterAuthRegisterPostData = {
  requestBody: RegisterRequest;
};

export type RegisterAuthRegisterPostResponse = TokenResponse;

export type LoginAuthLoginPostData = {
  requestBody: LoginRequest;
};

export type LoginAuthLoginPostResponse = TokenResponse;

export type RefreshAuthRefreshPostData = {
  refreshToken?: string | null;
};

export type RefreshAuthRefreshPostResponse = TokenResponse;

export type LogoutAuthLogoutPostData = {
  refreshToken?: string | null;
};

export type LogoutAuthLogoutPostResponse = void;

export type SearchIngredientsIngredientsSearchGetData = {
  limit?: number;
  q: string;
  unit?: UnitType | null;
};

export type SearchIngredientsIngredientsSearchGetResponse =
  Array<IngredientSearchResult>;

export type GetIngredientIngredientsIngredientIdGetData = {
  ingredientId: number;
};

export type GetIngredientIngredientsIngredientIdGetResponse = IngredientDetail;

export type UpdateIngredientIngredientsIngredientIdPatchData = {
  ingredientId: number;
  requestBody: IngredientUpdate;
};

export type UpdateIngredientIngredientsIngredientIdPatchResponse = IngredientDetail;

export type DeleteIngredientIngredientsIngredientIdDeleteData = {
  ingredientId: number;
};

export type DeleteIngredientIngredientsIngredientIdDeleteResponse = void;

export type CreateIngredientIngredientsPostData = {
  requestBody: IngredientCreate;
};

export type CreateIngredientIngredientsPostResponse = IngredientDetail;

export type PromoteIngredientIngredientsIngredientIdPromotePostData = {
  ingredientId: number;
};

export type PromoteIngredientIngredientsIngredientIdPromotePostResponse =
  IngredientDetail;

export type ListPromotionsAdminIngredientsPromotionsGetResponse =
  Array<IngredientDetail>;

export type ApprovePromotionAdminIngredientsPromotionsIngredientIdApprovePostData = {
  ingredientId: number;
};

export type ApprovePromotionAdminIngredientsPromotionsIngredientIdApprovePostResponse =
  IngredientDetail;

export type RejectPromotionAdminIngredientsPromotionsIngredientIdRejectPostData = {
  ingredientId: number;
  requestBody: PromotionRejectRequest;
};

export type RejectPromotionAdminIngredientsPromotionsIngredientIdRejectPostResponse =
  IngredientDetail;

export type ListSystemIngredientsAdminIngredientsGetResponse = Array<IngredientDetail>;

export type CreateSystemIngredientAdminIngredientsPostData = {
  requestBody: IngredientCreate;
};

export type CreateSystemIngredientAdminIngredientsPostResponse = IngredientDetail;

export type GetAnyIngredientAdminIngredientsIngredientIdGetData = {
  ingredientId: number;
};

export type GetAnyIngredientAdminIngredientsIngredientIdGetResponse = IngredientDetail;

export type UpdateAnyIngredientAdminIngredientsIngredientIdPatchData = {
  ingredientId: number;
  requestBody: IngredientUpdate;
};

export type UpdateAnyIngredientAdminIngredientsIngredientIdPatchResponse =
  IngredientDetail;

export type DeleteAnyIngredientAdminIngredientsIngredientIdDeleteData = {
  ingredientId: number;
};

export type DeleteAnyIngredientAdminIngredientsIngredientIdDeleteResponse = void;

export type BulkImportIngredientsAdminIngredientsBulkImportPostData = {
  requestBody: Array<BulkImportItem>;
};

export type BulkImportIngredientsAdminIngredientsBulkImportPostResponse =
  BulkImportResult;

export type ListUsersAdminUsersGetResponse = Array<UserAdminResponse>;

export type UpdateUserActiveAdminUsersUserIdPatchData = {
  requestBody: UserActivateRequest;
  userId: number;
};

export type UpdateUserActiveAdminUsersUserIdPatchResponse = UserAdminResponse;

export type UpdateUserRoleAdminUsersUserIdRolePatchData = {
  requestBody: UserRoleRequest;
  userId: number;
};

export type UpdateUserRoleAdminUsersUserIdRolePatchResponse = UserAdminResponse;

export type ListRecipesRecipesGetResponse = Array<RecipeSummary>;

export type CreateRecipeRecipesPostData = {
  requestBody: RecipeCreate;
};

export type CreateRecipeRecipesPostResponse = RecipeDetail;

export type GetRecipeRecipesRecipeIdGetData = {
  recipeId: number;
};

export type GetRecipeRecipesRecipeIdGetResponse = RecipeDetail;

export type UpdateRecipeRecipesRecipeIdPatchData = {
  recipeId: number;
  requestBody: RecipeUpdate;
};

export type UpdateRecipeRecipesRecipeIdPatchResponse = RecipeDetail;

export type DeleteRecipeRecipesRecipeIdDeleteData = {
  recipeId: number;
};

export type DeleteRecipeRecipesRecipeIdDeleteResponse = void;

export type DuplicateRecipeRecipesRecipeIdDuplicatePostData = {
  recipeId: number;
};

export type DuplicateRecipeRecipesRecipeIdDuplicatePostResponse =
  RecipeDuplicateResponse;

export type CalculateRecipeRecipesRecipeIdCalculatePostData = {
  recipeId: number;
  requestBody: CookRequest;
};

export type CalculateRecipeRecipesRecipeIdCalculatePostResponse = NutritionResult;

export type CookRecipeRecipesRecipeIdCookPostData = {
  recipeId: number;
  requestBody: CookRequest;
};

export type CookRecipeRecipesRecipeIdCookPostResponse = NutritionResult;

export type HealthHealthGetResponse = {
  [key: string]: string;
};

export type $OpenApiTs = {
  "/auth/register": {
    post: {
      req: RegisterAuthRegisterPostData;
      res: {
        /**
         * Successful Response
         */
        201: TokenResponse;
        /**
         * Validation Error
         */
        422: HTTPValidationError;
      };
    };
  };
  "/auth/login": {
    post: {
      req: LoginAuthLoginPostData;
      res: {
        /**
         * Successful Response
         */
        200: TokenResponse;
        /**
         * Validation Error
         */
        422: HTTPValidationError;
      };
    };
  };
  "/auth/refresh": {
    post: {
      req: RefreshAuthRefreshPostData;
      res: {
        /**
         * Successful Response
         */
        200: TokenResponse;
        /**
         * Validation Error
         */
        422: HTTPValidationError;
      };
    };
  };
  "/auth/logout": {
    post: {
      req: LogoutAuthLogoutPostData;
      res: {
        /**
         * Successful Response
         */
        204: void;
        /**
         * Validation Error
         */
        422: HTTPValidationError;
      };
    };
  };
  "/ingredients/search": {
    get: {
      req: SearchIngredientsIngredientsSearchGetData;
      res: {
        /**
         * Successful Response
         */
        200: Array<IngredientSearchResult>;
        /**
         * Validation Error
         */
        422: HTTPValidationError;
      };
    };
  };
  "/ingredients/{ingredient_id}": {
    get: {
      req: GetIngredientIngredientsIngredientIdGetData;
      res: {
        /**
         * Successful Response
         */
        200: IngredientDetail;
        /**
         * Validation Error
         */
        422: HTTPValidationError;
      };
    };
    patch: {
      req: UpdateIngredientIngredientsIngredientIdPatchData;
      res: {
        /**
         * Successful Response
         */
        200: IngredientDetail;
        /**
         * Validation Error
         */
        422: HTTPValidationError;
      };
    };
    delete: {
      req: DeleteIngredientIngredientsIngredientIdDeleteData;
      res: {
        /**
         * Successful Response
         */
        204: void;
        /**
         * Validation Error
         */
        422: HTTPValidationError;
      };
    };
  };
  "/ingredients": {
    post: {
      req: CreateIngredientIngredientsPostData;
      res: {
        /**
         * Successful Response
         */
        201: IngredientDetail;
        /**
         * Validation Error
         */
        422: HTTPValidationError;
      };
    };
  };
  "/ingredients/{ingredient_id}/promote": {
    post: {
      req: PromoteIngredientIngredientsIngredientIdPromotePostData;
      res: {
        /**
         * Successful Response
         */
        200: IngredientDetail;
        /**
         * Validation Error
         */
        422: HTTPValidationError;
      };
    };
  };
  "/admin/ingredients/promotions": {
    get: {
      res: {
        /**
         * Successful Response
         */
        200: Array<IngredientDetail>;
      };
    };
  };
  "/admin/ingredients/promotions/{ingredient_id}/approve": {
    post: {
      req: ApprovePromotionAdminIngredientsPromotionsIngredientIdApprovePostData;
      res: {
        /**
         * Successful Response
         */
        200: IngredientDetail;
        /**
         * Validation Error
         */
        422: HTTPValidationError;
      };
    };
  };
  "/admin/ingredients/promotions/{ingredient_id}/reject": {
    post: {
      req: RejectPromotionAdminIngredientsPromotionsIngredientIdRejectPostData;
      res: {
        /**
         * Successful Response
         */
        200: IngredientDetail;
        /**
         * Validation Error
         */
        422: HTTPValidationError;
      };
    };
  };
  "/admin/ingredients": {
    get: {
      res: {
        /**
         * Successful Response
         */
        200: Array<IngredientDetail>;
      };
    };
    post: {
      req: CreateSystemIngredientAdminIngredientsPostData;
      res: {
        /**
         * Successful Response
         */
        201: IngredientDetail;
        /**
         * Validation Error
         */
        422: HTTPValidationError;
      };
    };
  };
  "/admin/ingredients/{ingredient_id}": {
    get: {
      req: GetAnyIngredientAdminIngredientsIngredientIdGetData;
      res: {
        /**
         * Successful Response
         */
        200: IngredientDetail;
        /**
         * Validation Error
         */
        422: HTTPValidationError;
      };
    };
    patch: {
      req: UpdateAnyIngredientAdminIngredientsIngredientIdPatchData;
      res: {
        /**
         * Successful Response
         */
        200: IngredientDetail;
        /**
         * Validation Error
         */
        422: HTTPValidationError;
      };
    };
    delete: {
      req: DeleteAnyIngredientAdminIngredientsIngredientIdDeleteData;
      res: {
        /**
         * Successful Response
         */
        204: void;
        /**
         * Validation Error
         */
        422: HTTPValidationError;
      };
    };
  };
  "/admin/ingredients/bulk-import": {
    post: {
      req: BulkImportIngredientsAdminIngredientsBulkImportPostData;
      res: {
        /**
         * Successful Response
         */
        200: BulkImportResult;
        /**
         * Validation Error
         */
        422: HTTPValidationError;
      };
    };
  };
  "/admin/users": {
    get: {
      res: {
        /**
         * Successful Response
         */
        200: Array<UserAdminResponse>;
      };
    };
  };
  "/admin/users/{user_id}": {
    patch: {
      req: UpdateUserActiveAdminUsersUserIdPatchData;
      res: {
        /**
         * Successful Response
         */
        200: UserAdminResponse;
        /**
         * Validation Error
         */
        422: HTTPValidationError;
      };
    };
  };
  "/admin/users/{user_id}/role": {
    patch: {
      req: UpdateUserRoleAdminUsersUserIdRolePatchData;
      res: {
        /**
         * Successful Response
         */
        200: UserAdminResponse;
        /**
         * Validation Error
         */
        422: HTTPValidationError;
      };
    };
  };
  "/recipes": {
    get: {
      res: {
        /**
         * Successful Response
         */
        200: Array<RecipeSummary>;
      };
    };
    post: {
      req: CreateRecipeRecipesPostData;
      res: {
        /**
         * Successful Response
         */
        201: RecipeDetail;
        /**
         * Validation Error
         */
        422: HTTPValidationError;
      };
    };
  };
  "/recipes/{recipe_id}": {
    get: {
      req: GetRecipeRecipesRecipeIdGetData;
      res: {
        /**
         * Successful Response
         */
        200: RecipeDetail;
        /**
         * Validation Error
         */
        422: HTTPValidationError;
      };
    };
    patch: {
      req: UpdateRecipeRecipesRecipeIdPatchData;
      res: {
        /**
         * Successful Response
         */
        200: RecipeDetail;
        /**
         * Validation Error
         */
        422: HTTPValidationError;
      };
    };
    delete: {
      req: DeleteRecipeRecipesRecipeIdDeleteData;
      res: {
        /**
         * Successful Response
         */
        204: void;
        /**
         * Validation Error
         */
        422: HTTPValidationError;
      };
    };
  };
  "/recipes/{recipe_id}/duplicate": {
    post: {
      req: DuplicateRecipeRecipesRecipeIdDuplicatePostData;
      res: {
        /**
         * Successful Response
         */
        201: RecipeDuplicateResponse;
        /**
         * Validation Error
         */
        422: HTTPValidationError;
      };
    };
  };
  "/recipes/{recipe_id}/calculate": {
    post: {
      req: CalculateRecipeRecipesRecipeIdCalculatePostData;
      res: {
        /**
         * Successful Response
         */
        200: NutritionResult;
        /**
         * Validation Error
         */
        422: HTTPValidationError;
      };
    };
  };
  "/recipes/{recipe_id}/cook": {
    post: {
      req: CookRecipeRecipesRecipeIdCookPostData;
      res: {
        /**
         * Successful Response
         */
        200: NutritionResult;
        /**
         * Validation Error
         */
        422: HTTPValidationError;
      };
    };
  };
  "/health": {
    get: {
      res: {
        /**
         * Successful Response
         */
        200: {
          [key: string]: string;
        };
      };
    };
  };
};
